@echo off
setlocal EnableExtensions

cd /d "%~dp0"

set "APP_NAME=GreyNOC Stego Studio"
set "APP_PUBLISHER=GreyNOC"
set "APP_VERSION=1.0.0"
set "APP_ID={{9F9B6B6B-3E9A-4B42-9B3B-1F06C8B6C75B}"
set "EXE_NAME=GreyNOCStegoExtractor.exe"
set "SPEC_FILE=GreyNOCStegoExtractor.spec"
set "ICON_FILE=assets\greynoc_app.ico"
set "DIST_DIR=dist_release"
set "BUILD_DIR=build_release"
set "INSTALLER_DIR=installer_release"
set "ISS_FILE=GreyNOCStegoInstaller.iss"
set "SETUP_BASENAME=GreyNOCStegoStudioSetup"

if not "%~1"=="" set "APP_VERSION=%~1"

echo.
echo === GreyNOC release build ===
echo Version: %APP_VERSION%
echo.

if not exist "%ICON_FILE%" (
    echo [ERROR] App icon not found: %ICON_FILE%
    exit /b 1
)

if not exist "%SPEC_FILE%" (
    echo [ERROR] PyInstaller spec not found: %SPEC_FILE%
    exit /b 1
)

where python >nul 2>nul
if errorlevel 1 (
    echo [ERROR] Python was not found on PATH.
    exit /b 1
)

where pyinstaller >nul 2>nul
if errorlevel 1 (
    echo [ERROR] PyInstaller was not found on PATH.
    exit /b 1
)

echo Running tests...
python -m unittest -v
if errorlevel 1 exit /b 1

echo.
echo Wiping previous build outputs...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
    "$ErrorActionPreference = 'Stop';" ^
    "$root = (Resolve-Path -LiteralPath '.').Path;" ^
    "$targets = @('build','build_branded','build_updated','build_updated_escalated','build_release','dist','dist_branded','dist_updated','dist_release','installer_release');" ^
    "foreach ($target in $targets) {" ^
    "  $full = [IO.Path]::GetFullPath((Join-Path $root $target));" ^
    "  if (-not $full.StartsWith($root + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) { throw ('Refusing to delete outside workspace: ' + $full) }" ^
    "  if (Test-Path -LiteralPath $full) { Remove-Item -LiteralPath $full -Recurse -Force }" ^
    "}"
if errorlevel 1 exit /b 1

echo.
echo Building app executable...
pyinstaller --noconfirm --clean --distpath "%DIST_DIR%" --workpath "%BUILD_DIR%" "%SPEC_FILE%"
if errorlevel 1 exit /b 1

if not exist "%DIST_DIR%\%EXE_NAME%" (
    echo [ERROR] Expected executable was not created: %DIST_DIR%\%EXE_NAME%
    exit /b 1
)

if not exist "%INSTALLER_DIR%" mkdir "%INSTALLER_DIR%"

echo.
echo Generating Inno Setup script...
> "%ISS_FILE%" (
    echo ; Generated by build_release.bat. Manual edits are overwritten.
    echo [Setup]
    echo AppId=%APP_ID%
    echo AppName=%APP_NAME%
    echo AppVersion=%APP_VERSION%
    echo AppPublisher=%APP_PUBLISHER%
    echo DefaultDirName={autopf}\%APP_NAME%
    echo DefaultGroupName=%APP_NAME%
    echo OutputDir=%INSTALLER_DIR%
    echo OutputBaseFilename=%SETUP_BASENAME%
    echo SetupIconFile=%ICON_FILE%
    echo UninstallDisplayIcon={app}\%EXE_NAME%
    echo Compression=lzma
    echo SolidCompression=yes
    echo WizardStyle=modern
    echo ArchitecturesAllowed=x64
    echo ArchitecturesInstallIn64BitMode=x64
    echo.
    echo [Files]
    echo Source: "%DIST_DIR%\%EXE_NAME%"; DestDir: "{app}"; Flags: ignoreversion
    echo.
    echo [Icons]
    echo Name: "{group}\%APP_NAME%"; Filename: "{app}\%EXE_NAME%"; IconFilename: "{app}\%EXE_NAME%"
    echo Name: "{autodesktop}\%APP_NAME%"; Filename: "{app}\%EXE_NAME%"; IconFilename: "{app}\%EXE_NAME%"; Tasks: desktopicon
    echo.
    echo [Tasks]
    echo Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional icons:"
    echo.
    echo [Run]
    echo Filename: "{app}\%EXE_NAME%"; Description: "Launch %APP_NAME%"; Flags: nowait postinstall skipifsilent
)

set "ISCC="
for %%I in (iscc.exe) do set "ISCC=%%~$PATH:I"
if not defined ISCC if exist "%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" set "ISCC=%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe"
if not defined ISCC if exist "%ProgramFiles%\Inno Setup 6\ISCC.exe" set "ISCC=%ProgramFiles%\Inno Setup 6\ISCC.exe"

if defined ISCC (
    echo.
    echo Building installer...
    "%ISCC%" "%ISS_FILE%"
    if errorlevel 1 exit /b 1
) else (
    echo.
    echo [WARN] Inno Setup compiler was not found.
    echo [WARN] Installer script generated: %ISS_FILE%
    echo [WARN] Install Inno Setup and rerun this file to produce %INSTALLER_DIR%\%SETUP_BASENAME%.exe.
)

echo.
echo Release build complete.
echo App: %DIST_DIR%\%EXE_NAME%
if exist "%INSTALLER_DIR%\%SETUP_BASENAME%.exe" echo Installer: %INSTALLER_DIR%\%SETUP_BASENAME%.exe
echo Script: %ISS_FILE%

endlocal
