; Generated by build_release.bat. Manual edits are overwritten.
[Setup]
AppId={{9F9B6B6B-3E9A-4B42-9B3B-1F06C8B6C75B}
AppName=GreyNOC Stego Studio
AppVersion=1.0.0
AppPublisher=GreyNOC
DefaultDirName={autopf}\GreyNOC Stego Studio
DefaultGroupName=GreyNOC Stego Studio
OutputDir=installer_release
OutputBaseFilename=GreyNOCStegoStudioSetup
SetupIconFile=assets\greynoc_app.ico
UninstallDisplayIcon={app}\GreyNOCStegoExtractor.exe
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Files]
Source: "dist_release\GreyNOCStegoExtractor.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\GreyNOC Stego Studio"; Filename: "{app}\GreyNOCStegoExtractor.exe"; IconFilename: "{app}\GreyNOCStegoExtractor.exe"
Name: "{autodesktop}\GreyNOC Stego Studio"; Filename: "{app}\GreyNOCStegoExtractor.exe"; IconFilename: "{app}\GreyNOCStegoExtractor.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional icons:"

[Run]
Filename: "{app}\GreyNOCStegoExtractor.exe"; Description: "Launch GreyNOC Stego Studio"; Flags: nowait postinstall skipifsilent
